### ISSUE TITLE
PHP error in functions file

### ISSUE THREAD

**Issue by Chillifish** [tidythemes/blankslate#1]
Getting the following error:

Only variables should be passed by reference in /wp-content/themes/blankslate/functions.php on line 116

Removing the & in `$comments_by_type = &separate_comments( get_comments( 'status=approve&post_id=' . $id ) );` has fixed the issue with me, but I have no idea if that will cause issues as I don't know why it was there in the first place.

**Comment by Stanowczo** [comment]
Got the same. Instead of modifying the function you may also call 
`error_reporting(E_ALL & ~E_STRICT);`
in functions.php so that no "strict standard" error will show up.
