### ISSUE TITLE
Announcement, Suggestions, and Updates

### ISSUE THREAD

**Issue by bhadaway** [tidythemes/blankslate#10]
Hi Everyone,

Creator of BlankSlate here.

It's been about 4 years now since I was officially involved in the project.

I was trying to see if I could get involved in the project again in any official capacity, but it doesn't look like that's going to happen.

That said, the project isn't abandoned, and with tens of thousands of websites depending on it as a foundation, it'll live on. BlankSlate, mostly due to its simplicity (which is the entire point), has always been extremely stable.

Still, I'd very much like to hear some feedback on some things that should be added or removed for the last few rounds of updates I'll be making here, to leave something even better and more stable for years to come.

You'll notice already with the 2019 updates, that I've made a lot of important updates to keep the project up-to-date with theme review requirements. But, also, I introduced a few new issues:

1. Duplicate calls to `the_content()` — Obvious human error on my part. Fixed and will be in the next update.
2. I added some aggressive styles to the reset. Some of these, like CSS transitions, are definitely not a good fit for BlankSlate. This was an oversight on my part. Removed and will be in the next update.

Anything else?

Mostly, I imagine I'll be removing things, things that you've found out in the wild almost never come up on a project, and you find yourself stripping out over and over again. For example, has anyone found the browser classes helpful?

Thank you.

**Comment by pattonwebz** [comment]
Hey :wave: 

I had not previously heard of this project before this week but it's kind of cool. Watching where it goes :)

Thanks for dealing with the duplicate calls issue I reported so quickly.

**Comment by leecollings** [comment]
This is literally the ONLY Wordpress theme I ever use.

I actually did end up forking it again, I’m going to probably bring my
version back to prior the 2019 update.

Essentially I use it for the files and that’s it. Maybe the after setup
function in the functions file too.

Everything else including the contents is per individual, so that’s why I
think pretty much all of the 2019 commit includes what I would say
unneccessary additions. I didn’t think there was anything wrong with it
prior.

**Comment by bhadaway** [comment]
@pattonwebz — The project is pretty old, about 8 years now. It even predates Underscores. It was quite an interesting challenge getting it accepted onto WordPress.org the first time around, with some confused reviewers, theme users, and other people out in the wild that just didn't get it:

https://premium.wpmudev.org/blog/10-fugly-wordpress-themes/

Of course, in the end, enough people (the right people) got the concept obviously, with 10k+ active sites using it, which doesn't account for the countless other websites and themes that are built on it, where they swapped out the name, as recommended.

I think a lot of people use it simply as a base and then child theme in just the styles they need, which is pretty cool, and not something I had fully expected at first. As for where it goes from here, I'm not sure, as I said, it's no longer my baby.

The website is a complete mess, and I'd love to personally overhaul everything and bring it into 2019, new logo, SSL, redesign, etc. The new owner says he'll be looking into making those improvements himself.

Outside of that, the manifesto I wrote here still holds pretty true to how I feel today:

http://tidythemes.com/concept/

And I think I've made some important updates to BlankSlate to keep it stable for some time to come, regardless of how it evolves now.

You're welcome. I'd love to continue maintaining the project and be even faster with updates and support, but again, it's not my project anymore, so I must move on once and for all.

PS: Is there a known issue with the dev logs, subversion repo, and trac right now? I'm getting a 403 when I try to access any of them.

@leecollings — Other than the aggressive CSS I added that definitely needed to be removed, most of the updates are very important. I modernized the code, updated some things based on new theme review guidelines and WordPress 5.0, I think I fixed some PHP 7 errors, and most importantly, improved security by escaping echos. All good, non-intrusive updates. I highly recommend forking from version 2019.1.

If you're still not sure, please take this opportunity to make some suggestions, and if they're not too highly specific, and make sense for the majority of users, I'll consider them. But, I'll only be around for another day or so to make sure everything is in order.

Thank you.

**Comment by bhadaway** [comment]
Just a heads up that I'll be closing out this issue tonight and moving on from the project.

If anyone has any feedback to make it into a last minute update here, speak now, or forever hold your peace. :P

**Comment by pattonwebz** [comment]
I have nothing to add but I want to say good luck to you in your future projects :)

**Comment by bhadaway** [comment]
Thanks. :)

**Comment by thammarith** [comment]
Hi, just found this discussion and want to add a suggestion.

I think you should use GitHub's release for releaseing. It'll notify the watchers so we can come and check it out easily.

Thank you for this it's really the only starter theme I use.
