### ISSUE TITLE
woocommerce and Product comments not work? 

### ISSUE THREAD

**Issue by SpaceG** [tidythemes/blankslate#11]
Hello, when you also install woocommerce, the comments for the customer review does not work? Any idea to fix this.=? Thanks.

**Comment by leecollings** [comment]
This doesn’t have anything to do with BlankSlate.

The idea is that you take this template as is and built into your own
custom template.

You need to built it to work with WooCommerce.

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
