### ISSUE TITLE
Cannot delete featured image

### ISSUE THREAD

**Issue by kbasude** [tidythemes/blankslate#14]
Hello,
I updated the theme and it messed with my websites quite a bit. I managed to delete the search bar, additional heading, search bar, etc, but I can't get the strangely placed featured image to go away. I inspected the element and found its class, and I renamed its class and tried to get rid of it with "display: none" but it is strangely connected to my website, so when I do that it deletes everything on the page.

The website is krishnabasude.com. You will see the huge featured image at the top. Any advice is greatly appreciated.

**Comment by leecollings** [comment]
Sorry, but I can't see what the problem is? This isn't a problem with the theme, it's a modification you've made after it.

This theme isn't meant to be used 'as is', there technically is no support for it. When you download it, you are to manipulate it as you wish.

**Comment by kbasude** [comment]
Hi Lee,
I know, that's what I am trying to do, I am trying to manipulate it and need some help. The problem is that there is a gigantic photo at the top of my website pages. That is definitely a problem. Is it NOT a modification I made.
Originally it worked perfectly and I was able to modify it myself to remove headers, but somehow updating the theme added the featured photo in an enlarged size to all pages.

**Comment by leecollings** [comment]
You probably want to be looking somewhere in your template files for `the_post_thumbnail()` thats appearing at the top of everything.

**Comment by leecollings** [comment]
If you email me with access to your Wordpress site I could probably quickly fix it for you.

**Comment by kbasude** [comment]
My mofidications have been almost none so far besides some CSS stuff that I have added through WordPress' "Edit CSS" box.
I was hoping someone more experienced could inspect elements and find how to remove the photo.

I will try to check for the template file again. I thought I was able to find it and change the class name so I could just hide it, but somehow doing that hides the entire page...

I appreciate it, I will try to send you a copy of my site or something today

**Comment by leecollings** [comment]
Personally I'm offended that you don't think I'm someone more experienced.

For the record I was able to simply insert `display:none;` direct on the image and that removed it, so you could do if you want a quick fix.

This issue has nothing to do with CSS, it's to do with the template files.

**Comment by kbasude** [comment]
Bro... I meant someone more experienced than ME, not referring to you there haha. 
Hmm awesome. I will try to find it in template files. and just say "display: none" directly instead of referring to its class. Will update if that doesn't work

**Comment by leecollings** [comment]
Well yes, you only want to hide the photo, not the class (as setting the class to display none will apply to it all other elements with the same class).

But you don't want to just hide the image, you want to remove it from the markup entirely.

From memory, look in the entry-content.php file, I have a feeling it may be in there at the top somewhere.

**Comment by leecollings** [comment]
I think I've found where your issue is, #9 in page.php:

`<?php if ( has_post_thumbnail() ) { the_post_thumbnail(); } ?>`

**Comment by kbasude** [comment]
Yea that makes sense.

I had actually already tried that. I deleted everything from entry-content.php (it's literally empty" but somehow the header, search bar, and photo were still showing up. 
Thanks for all your help so far by the way

Oh nice, let me see if messing with that fixes it.

**Comment by leecollings** [comment]
>  I deleted everything from entry-content.php (it's literally empty" but somehow the header, search bar, and photo were still showing up.

Yes, they will because all that stuff isn't in the entry-content.php file, it's in the header.php file.

The entry.php files are only for the main Wordpress article on the page.

**Comment by kbasude** [comment]
Okay deleting line 9 worked perfectly. I remember messing with that file before but I think I removed line 10 and that might have been the issue.
Thanks so much for your help.

**Comment by leecollings** [comment]
No worries, just bear in mind this has now removed your featured image from the page template, just incase you end up with other pages trying to add it in and can't find it... this is why.

**Comment by kbasude** [comment]
It should be fine, because now when I check the link with Facebook Sharing Debugger, the featured photo still shows as the thumbnail, but the photo itself isn't displayed as a huge photo on my website. Thanks again

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
