### ISSUE TITLE
change max-width of main page content

### ISSUE THREAD

**Issue by rabbitsfootfetish** [tidythemes/blankslate#15]
Hi. The text on the main index page stretches all the way to the edge of the screen on desktop. I've successfully set a max-width of 700px for posts and single pages, but nothing seems to work when I attempt to set a max-width for the content of the main index page. I know it has to be a really simple fix, but I haven't been able to figure it out. I could just cheat and creat a new page and set that to be the homepage, but I'd like to avoid doing that.  There's probably just one line of code that I could add, and I'm just not getting it.

url in question is http://www.rabbitsfoot.net

**Comment by rabbitsfootfetish** [comment]
Nevermind . Figured it out. Had to change the .wrap max-width and that did the trick

**Comment by DCollepa** [comment]
Hey! Do you happen to remember the solution? I've been having this same issue, with some pages stretching a bit more than I want them to. Thanks!

**Comment by bhadaway** [comment]
You probably want:

```
#wrapper {
	max-width: 800px;
	margin: 0 auto;
}
```
