### ISSUE TITLE
Elementor

### ISSUE THREAD

**Issue by dineend71** [tidythemes/blankslate#17]
Good afternoon

Could someone please confirm if I can use Elementor Page Builder with the BlankState theme?  Thank you.

**Comment by leecollings** [comment]
Yes, as long as you include calls to `the_content()` in your template files.

**Comment by dineend71** [comment]
Hi Lee, thanks for your reply.  How would I go about doing the above?  I've only built a few sites using Elementor page builder, however, I'm potentially taking over the management of a website using BlankSlate theme.  Thanks.

**Comment by leecollings** [comment]
Okay, you realise BlankSlate is used to create your own themes right?

So you take it and do what you want to do to it, so I can’t tell you exactly how it has to be, but as long as you’re calling the_content() in your template files, Elementor will be used within that.

**Comment by dineend71** [comment]
Hi Lee, I can confirm that the activated theme is a child theme with it's own name (not using BlankSlate).  Do you know where the template files would typically be found?  The guy who originally developed the site isn't being used to maintain the site going forward and he isn't being very forthcoming with information.  Reason I'm asking is that the customer wants a certain section on the homepage removed, yet when I edit the home page within WordPress I can't find that content anywhere?
Thanks.

**Comment by leecollings** [comment]
Okay, I don’t think you’re asking in the right place then. Is the parent theme on the website BlankSlate..? And has it been modified do you know?

The only call that Elementor uses is the_content(). It sounds as though you have a more specific set up with your website that is unrelated to BlankSlate.

**Comment by leecollings** [comment]
Can I see the site and the content you’re referring to? That might help me identify where you should be looking.

**Comment by dineend71** [comment]
Hiya Lee, thanks for your reply.  The site is https://madeinheresouthampton.com/ and the content which the customer wants to remove is towards the end of the homepage, the section in question is where is says "Gifts made exclusively for Made in Here".  When I edit the homepage in WordPress I can't find anything in relation to that section, so I'm struggling to find where to find the content.  Thanks.

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
