### ISSUE TITLE
Complete Newby to WordPress

### ISSUE THREAD

**Issue by derekweaver** [tidythemes/blankslate#18]
I have hand coded one web page for my sweetheart, lifecasting.net. We are moving in new directions with art made from bone. I want to make a responsive site and have been told that WordPress is a fabulous way to do this.

In reviewing the "issues" that others have had, I am wondering if I need to go for something even more simplistic, if that exists. As I have no idea what .php is, nor do I enjoy javascript.

I had chosen this theme as it seemed most adaptable to my desires. If I am going to be monkeying around under the hood with java script do recommend finding another theme?

Any thoughts for a complete novice?

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
