### ISSUE TITLE
Beaver Builder is causing issues with BlankSlate

### ISSUE THREAD

**Issue by chud37** [tidythemes/blankslate#19]
I'm not sure where the problem lies, but I thought I'd ask here.

So I'm trying build my own theme using BlankSlate as a base.  At the bottom of functions.php, I've written the following:

```
    wp_deregister_script('jquery'); // Remove WP jQuery version
    wp_enqueue_script('jquery', 'http://code.jquery.com/jquery-3.5.1.min.js', array(), '3.5.1', true );
```

I need to use jQuery on my website.

So it all works fine, but then I try and use Beaver Builder.  When I try and edit a page using BB, the editor simply doesnt load anymore, and I get multiple errors in my console:

```
Mixed Content: The page at 'https://labs.awme.net/?fl_builder' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-3.5.1.min.js?ver=3.5.1'. This request has been blocked; the content must be served over HTTPS.
header.js?ver=5.5.3:5 Uncaught ReferenceError: $ is not defined
    at header.js?ver=5.5.3:5
(anonymous) @ header.js?ver=5.5.3:5
`core.min.js?ver=1.11.4:11 Uncaught ReferenceError: jQuery is not defined
    at core.min.js?ver=1.11.4:11
    at core.min.js?ver=1.11.4:11
(anonymous) @ core.min.js?ver=1.11.4:11
(anonymous) @ core.min.js?ver=1.11.4:11
widget.min.js?ver=1.11.4:11 Uncaught ReferenceError: jQuery is not defined
    at widget.min.js?ver=1.11.4:11
    at widget.min.js?ver=1.11.4:11
(anonymous) @ widget.min.js?ver=1.11.4:11
(anonymous) @ widget.min.js?ver=1.11.4:11
mouse.min.js?ver=1.11.4:11 Uncaught ReferenceError: jQuery is not defined
    at mouse.min.js?ver=1.11.4:11
    at mouse.min.js?ver=1.11.4:11
(anonymous) @ mouse.min.js?ver=1.11.4:11
(anonymous) @ mouse.min.js?ver=1.11.4:11
jquery.ui.sortable.js?ver=2.4.0.5:1298 Uncaught ReferenceError: jQuery is not defined
    at jquery.ui.sortable.js?ver=2.4.0.5:1298
(anonymous) @ jquery.ui.sortable.js?ver=2.4.0.5:1298
```

(The errors are longer, but I just put the first few).

I've also seen that in my <head> for the website, I've got the following:
`<script type="text/javascript" src="https://labs.awme.net/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp" id="jquery-core-js"></script>`

Why / what is loading such a low version of jQuery? I can see in Blankslate, near there top it has this line:
`wp_enqueue_script('jquery');`

Which I think my code (at the bottom of functions.php) is causing problems with (unregistering `jquery`).

I just want to build a good theme using Beaver Builder and JQuery, and I have no idea what I'm doing wrong.  Any help, please?

**Comment by leecollings** [comment]
Is there any particularly reason why you're telling Wordpress NOT to use the built in version of jQuery and then loading your own one?

Have you tried just using wp_enqueue_script('jquery') and seeing how it works?

The message you get about not using https, is because your URL to jQuery is not using https.

The further errors are likely to be because Wordpress uses non-conflict jQuery (using jQuery instead of $).

I'd like to know what happens if you remove all of your own inclusion of jQuery and stick with the Wordpress default.

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
