### ISSUE TITLE
nice but...

### ISSUE THREAD

**Issue by michaelscheurer** [tidythemes/blankslate#2]
why all the code is written without any space or tab? it's simply unreadable... it's a pity!

**Comment by leecollings** [comment]
Because it's an extremely minified template, designed not to be bloated.

**Comment by napolux** [comment]
Code format for PHP should be applied IMHO.

**Comment by leecollings** [comment]
But isn't the point of this template that people download it and use it to suit their needs?

Not just to use as is.

I've been thinking of forking this and keeping it updated with new Wordpress functions and some basic customisable options. Maybe I'll expand it at the same time.

**Comment by napolux** [comment]
@leecollings At least readability should be given.
I forked it for the same reasons ;)

**Comment by napolux** [comment]
@leecollings check https://github.com/napolux/blankslate
