### ISSUE TITLE
Offer to takeover repo

### ISSUE THREAD

**Issue by leecollings** [tidythemes/blankslate#21]
Hi there,

I notice you haven't made any updates to this since April last year.

I would like to ask if you wouldn't mind, would I be able to take the project over from you and move it to my own account instead?

I would be more than happy to respond to issues and provide updates to this if you are unable to or don't have the time or resources to keep the project going.

Let me know if you'd be interested!

Thanks,
Lee

**Comment by webcodedesigner** [comment]
Hi Lee. I've forked this project, and you can find it at https://github.com/webcodedesigner/Nada.git
If you're still interested, please feel free to contribute. Looking forward to hearing from you!

**Comment by agirlandhermac** [comment]
I'm using this theme on a Woo/Printful shop so I have some concerns about the theme seemingly having been abandoned. I do hope someone, whether it's tidythemes or Lee or anyone else, keeps it updated. I'm very thankful it's out there and I'm able to use it, and It's so bare bones my concerns are minimal, but still. No one wants to see that the theme they're using hasn't been touched in almost 2 years...

**Comment by leecollings** [comment]
Just an update to anyone who stumbles across this, I've created a new version of this over at https://github.com/leecollings/SimplyBlankslate which will be updated frequently.

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!

**Comment by agirlandhermac** [comment]
> Just an update to anyone who stumbles across this, I've created a new version of this over at https://github.com/leecollings/SimplyBlankslate which will be updated frequently.

@leecollings Hi Lee, just wanted to check that you'll still be maintaining SB. I noticed there wasn't a way to open an issue (I don't need to right now) so just checking. Thx!
