### ISSUE TITLE
White Screen Appears, Cannot Edit or Add new post in Wordpress

### ISSUE THREAD

**Issue by kjeldzen** [tidythemes/blankslate#22]
Hi,

The website works fine. However, I cannot add or edit new posts using the WordPress editor nor Elementor Page builder. If I add a new post it appears blank white page. I tried to troubleshoot by disabling the plugins, clearing cache, etc but it still not working.

Now, when I change it to default theme twenty, the add new post/page has worked. So, I suppose the problem is the blank slate theme and I do not have an idea how to fix it unless I change the theme completely which is not practical at this point.

![image](https://user-images.githubusercontent.com/74638572/99480609-610b6480-2993-11eb-8543-bd87398ca071.png)

Please help me.

**Comment by bhadaway** [comment]
Hello,

Original creator of BlankSlate here. I'm sorry for the long hiatus, but I have been given permission to once again manage the project. So, I will again be pushing code updates and helping with user support.

Please let me know if you still need help with this specific issue and even if not, I would still like to get your feedback anyway:

https://wordpress.org/support/topic/important-announcement-3/

Thanks!
