### ISSUE TITLE
Important Announcement!

### ISSUE THREAD

**Issue by bhadaway** [tidythemes/blankslate#23]
Hi BlankSlate Users,

Original creator of the project here. I just wanted to let everyone know that I will again be maintaining the code and providing user support daily on a volunteer basis (I would appreciate any support you can give for this effort: https://calmestghost.com/donate). Despite the previous long hiatus, please know that the project is not abandoned.

I'm preparing for a major upgrade, but with over 10k active users, I don't want to go in all guns a blazin'. Please take this opportunity to share your feedback about how you use the project, what you'd like to see added, what you'd like to see removed, what you don't want to change, etc.

Now's the time! I'm listening. Please share your feedback below or if you wish to share feedback privately:

bhadaway@gmail.com

Thanks

**Comment by cpgb85** [comment]
I wouldn't do this project, I would create a new "blankslate 2" project. Leave this as legacy.

**Comment by bhadaway** [comment]
@cpgb85 — While I understand the sentiment, that people don't like change, and that in an ideal world there would be a perfect or complete version of something where no further tampering would be required, unfortunately the world just doesn't work that way, especially when it comes to the digital world.

If there were to be an untouched legacy version and a new version, essentially the legacy version would eventually just stop working and then the new version would be *the* main version. It doesn't really make sense and the longer we wait, the worse it gets.

Rather than letting the original BlankSlate die and eventually all those sites that rely on it breaking down, why not keep it up-to-date with web standards and WordPress guidelines? In fact, with the exception of these past 2 years, this has always been the case for the project.

I understand the fear with theme and plugin authors and some of the extremely poor decisions they've made (some recent examples in mind) where they completely destroyed the original concept and betrayed the users. That's not what's happening here. I'm still a minimalist; I still fully intend on keeping the overall template structure and primary code layout the same; I'll just be making surgical improvements for things like: valid code, accessibility, SEO, schema, etc.

With the exception of people that built their sites in completely insane and incorrect ways like just editing the theme directly without using a child theme or changing the name or setting the version number to something that would disable updates, the noticeable changes should be extremely minor. I won't pretend that it's not possible that you might have to spend 10 min changing a handful of styles, but the sky shouldn't fall.

In any case, this is why I'm here exercising extreme caution and awaiting further feedback.

**Comment by cpgb85** [comment]
I for one use your theme when creating projects.  I use it as a parent theme, and make all changes to the child theme.   The problem with putting out an extreme update like this on this project that could break tons of websites is that it can lead to some very angry people. yes it will eventually stop working, but that's when we can tell the client they need to be upgraded.  I'm certain I'm not the only person in this boat.  I still think this being a legacy version and creating an updated blankslate would be the way to go.

**Comment by bhadaway** [comment]
Here's what I'll do. Once the update is ready, I'll push everything to GitHub first. That way, you and other users can preview the code first and let me know if anything in there gives you any concerns. And once we're all comfortable with it, then I'll push it live on wordpress.org. Ultimately, this should be a good thing. BlankSlate is dated and this code will improve your websites; that's the point. I promise I care and am not here to murder websites.

**Comment by cpgb85** [comment]
I would say in my opinion, for me. keep the menu registration.   95% of my clients won't matter since they don't update their websites at all. It's just something i have to keep my eye on because some of my clients pay me to update their stuff.

**Comment by bhadaway** [comment]
The menu won't change; most things like that won't.

**Comment by bhadaway** [comment]
Here's the proposed code for version 2021:

https://github.com/tidythemes/blankslate/commit/674957aa17545609bc69cb03fa77933671afd54e#diff-6a43b5114832fb0dcda5e956088b6d5402661e008d8aa8e994d04f872ac1b995

New:

1. Name has been changed from **BlankSlate** to **Blankslate**
2. Schema markup now baked into the HTML structure
3. Accessibility improvements
4. Header search form moved to below the menu (better for proper styling and accessibility tab order)
5. Call to sidebar moved to just _footer.php_ do avoid unnecessary redundancy
6. Removed _/languages/_ folder
7. Various other code fixes and minor cleanup

Here are some additions that I've carefully omitted out of caution, although people might actually appreciate these being added:

1. Custom logo upload
2. Lightweight jQuery script to automatically make videos responsive
3. Mobile menu icon and jQuery for opening and closing menu
4. Starter styles (after reset, at least preparing very basic tags like _<strong>_ and _<em>_)

That's it. As you can see, some well-needed dusting, but nothing catastrophic.

_**NOTE**: This code has only been pushed to GitHub for your review. I'll wait a few more weeks before actually pushing it live to wordpress.org, so now's the time to share any concerns or requests._

Thank you!
