### ISSUE TITLE
Use Case-

### ISSUE THREAD

**Issue by alittleoilandluck** [tidythemes/blankslate#24]
I am using this plugin in order to be able to use a low-code db builder. I use elementor to design my site and when I embedded code using the default Elementor theme, it would overwrite all of the css for the database that  I had configured on the service. I have just started using this, but so far, this seems to be a life saver for at least being able to post. 

As for the LC builder  Im using, it is Caspio (caspio.com). You might even reach out to them if you wanted to do a spin off, specifically geared towards allowing their users to easily embed 'widgets' while maintaining 'theme' (on caspio), integrity.

Thank you for building this, once I am sure it fits my needs, I will definitely donate!

**Comment by bhadaway** [comment]
Thanks for the feedback.

Although I've thought about building themes, plugins, templates, and add-ons for other platforms over the years, my time is just spread too thin. If it's not something I use myself, it's just not gonna happen.

**Comment by alittleoilandluck** [comment]
All good. Just left the message to give you another use case for it.

Thank you for the response and the product!

Typos Courtesy of:

Outlook for Android<https://aka.ms/ghei36>

________________________________
