### ISSUE TITLE
Theme not updating via ManageWP

### ISSUE THREAD

**Issue by agirlandhermac** [tidythemes/blankslate#26]
Hi! Just wanted to let you know the theme won't update via ManageWP. I've tried a few times with no success. Thanks!

**Comment by bhadaway** [comment]
You're referring to https://managewp.com/? This is a plugin that helps you auto-update themes and plugins? Note that WordPress also now has this feature baked right in.

Anyway, hmm, my guess would be that the way ManageWP handles/looks for version numbers, it might be confused my the format I use, 2021.

I think you'll just need to manually update it.

**Comment by agirlandhermac** [comment]
Having to update manually isn't a big deal, but I did that and Woo is jacked. I removed my CSS and deactivated my child theme to see if it was what I added but it's not, Woo elements like the featured image aren't showing up. I can post a separate issue about Woo if necessary but based on your last response and immediately closing the issue it doesn't feel like you're actually open to addressing any issues.

**Comment by bhadaway** [comment]
Please don't worry about the closed status. As you can see, it doesn't actually "close" the topic in the traditional sense where it would prohibit you from replying further, otherwise I wouldn't use it.

Anyway, I'm always here to help you, as best as I can! :)
