### ISSUE TITLE
WooCommerce reviews not displaying properly

### ISSUE THREAD

**Issue by justingoboom** [tidythemes/blankslate#29]
Hello. I used Blankslate to build out a theme for a client and I recently ran into an issue when we decided to add WooCommerce. The issue has to do with the way reviews (comments) are displayed. The reviews do not show up in the tabbed area as they should and are displayed as traditional comments at the bottom of the product page. I deactivated all plugins, except for WooCommerce, and changed themes to Twenty Twenty One to test and it works as it should. I even tried another blank style theme called _s, to see if it was something I created for myself as I customized Blankslate, but the same issue of the reviews not displaying/functioning as the should presented itself. So my question to you is this, what is missing from your theme that exists in Twenty Twenty One to make the reviews display as they should?

You can see the issue on display in these screenshots:

1. My theme built on Blankslate. Reviews not in tabbed section as expect, situated in normal comment position.
https://www.dropbox.com/s/fgi8z0g6yskaqki/currantc-currantc.jpg?dl=0

2. Blankslate. Reviews not in tabbed section as expect, situated in normal comment position.
https://www.dropbox.com/s/p55nkr9dix4bp92/currantc-blankslate.jpg?dl=0

3. Twenty Twenty One. Reviews in tabbed section as expect.
https://www.dropbox.com/s/5wqfd5r3myyu727/currantc-2021.jpg?dl=0

By the way, I am a big fan of Blankslate. It makes building custom themes so much easier than trying wrangle with some other theme's crap.

**Comment by bhadaway** [comment]
I believe you're only testing this right now, but is there any chance you could make this live just so that I can view it for a bit?

**Comment by justingoboom** [comment]
Here is a test product page that features a test comment: https://www.currantc.com/store/preserves_test/currantc-black-currant-preserves-test/

Thanks for the help and sorry to bother you about this, especially if have a lot going on in another part of your life. Don't worry, I'm not stalking this thread waiting for to reply, I just happened to look at it right as you posted your comment.

**Comment by bhadaway** [comment]
Hmm, this might be as simple as adding the following to your _functions.php_ file:

`add_theme_support( 'woocommerce' );`

If that's really all that it is, I'll officially add it to the project.

**Comment by justingoboom** [comment]
That did it! Thanks. Now I have to deal with other things like an "rslides" set of classes being added to the contents of the reviews tab making it rotate like a slider. Not sure why, but that is not of your concern, so again thanks for the help!

**Comment by bhadaway** [comment]
You're welcome.
