### ISSUE TITLE
Type for itemprop is not specified

### ISSUE THREAD

**Issue by robertandrews** [tidythemes/blankslate#34]
In a couple of areas, W3C HTML Validator reports:

`The itemprop attribute was specified, but the element is not a property of any item.`

- Multiple when echoing the site name and description
- Post titles

This [StackOverflow answer ](https://stackoverflow.com/a/29124838/1375163)says:

> You should explicitly provide a type these properties (name, description, image) belong to.
>
> In Schema.org, everything is a Thing. Thing has many child types, listed under "More specific Types". Start there and choose the most specific type for your content.
>
> For example: WebPage, Article or maybe BlogPosting.
>
> It could look like (using WebPage as example here):
>
> <html itemscope itemtype="http://schema.org/WebPage">

Were you leaving the type blank for end users, given the range of options?

**Comment by bhadaway** [comment]
Thank you for all the feedback!

Fixed. (correct me if I'm wrong)

Of all the issues you raised:

1. `span` wrapping `p` issue — This was just an oversight.
2. `datetime` format issue — This is something I went back and forth on, and decided to remove, but just didn't think validation was necessary.
3. `schema` issue — This one has been a constant pain point when it comes to the review process on wordpress.org. One admin/reviewer tells be it's allowed and another tells me it isn't. It seems to be a gray area on whether it's "plugin territory" or not. I make a case for it being theme territory, and entirely appropriate to bake schema right into the theme code.
