### ISSUE TITLE
Unable to install the latest version of BlankSlate: 5.9.2.

### ISSUE THREAD

**Issue by dgofman** [tidythemes/blankslate#37]
BlankSlate
By Bryan Hadaway 
5.0 rating based on 50 ratings [(50 ratings)](https://wordpress.org/support/theme/blankslate/reviews/)
Version: 2022.1
This theme doesn’t work with your version of PHP. [Learn more about updating PHP](https://wordpress.org/support/update-php/).

Please read: tidythemes.com/concept. Donations: https://calmestghost.com/donate. BlankSlate is the definitive WordPress boilerplate starter theme. We've carefully constructed the most clean and minimalist theme possible for designers and developers to use as a base to build websites for clients or to build completely custom themes from scratch. Clean, simple, unstyled, semi-minified, unformatted, and valid code, SEO-friendly, jQuery-enabled, no programmer comments, standardized and as white label as possible, and most importantly, the CSS is reset for cross-browser-compatability and no intrusive visual CSS styles have been added whatsoever. A perfect skeleton theme. For support and suggestions, go to: https://github.com/tidythemes/blankslate/issues. Thank you.

![image](https://user-images.githubusercontent.com/147298/159139718-dddb774b-0d43-4f2e-99ec-b6a385abfe4f.png)

**Comment by bhadaway** [comment]
Fixed!
