### ISSUE TITLE
Change <time> title attribute to human-readable

### ISSUE THREAD

**Issue by robertandrews** [tidythemes/blankslate#38]
Re: https://github.com/tidythemes/blankslate/commit/e8039d508d376b9c62a857048489395263c5b20a#r69082856

> Not sure if the title attribute should also use the same fully machine time as datetime.
https://css-tricks.com/time-element/#aa-other-bits

You used machine-readable datetime stamp as the title attribute. This attribute, I think, is more intended to be human-readable. People say it's for showing tooltips.

**Comment by bhadaway** [comment]
Done. Pushed to GitHub now and will be pushed to WordPress later (in the next update).
