### ISSUE TITLE
No CSS

### ISSUE THREAD

**Issue by mac2net** [tidythemes/blankslate#4]
In my implementation with a child theme, I removed the stylesheet. 
This way the theme works with browser defaults which is kind of cool.

**Comment by leecollings** [comment]
I'm not sure I agree that it's cool to use Browser defaults, as this can cause your website to look different in different browsers, which isn't ideal if you've got a brand you're trying to stick to.

As for a child theme implementation, you shouldn't need to remove the stylesheet at all, you could use a function in your child's functions.php file to just deregister the Blankslate CSS file, which would remove the resets, as that's all it offers anyway.

The theme itself doesn't actually have any CSS rules.

Also, using Blankslate as a parent theme, and then using a child theme isn't the best way to be using the theme, I believe you're supposed to take it, and literally make changes directly to the theme to suit your needs, but please correct me if I'm wrong.

So I don't really think this is an issue as such...

**Comment by mac2net** [comment]
Yes that's what I did.
I use blankslate to demo different sites for downloading a web page to be read offline.
A lot of these pages use browser defaults.
There are a lot of theories about CSS resets so results also can be inconsistent.
