### ISSUE TITLE
Error when upgrading to the latest theme

### ISSUE THREAD

**Issue by iainelite** [tidythemes/blankslate#43]
Once we upgrade the site shows a basic wireframe. (attached). Also, the following error was found.

WARNING: [pool site-elitetransit.com] child 48 said into stderr: "NOTICE: PHP message: PHP Fatal error: Uncaught Error: Call to undefined function get_field() in /www/wp-content/themes/blankslate/header-home.php:20"”

![contact capture](https://user-images.githubusercontent.com/108297230/176011036-02dfc939-b706-435b-af92-9fe755b56903.PNG)

**Comment by iainelite** [comment]
Someone else designed our site. We simply upgraded and it broken, we restored a backup, so we are ok ...but stuck on an old theme.

Thanks



IAIN MACLEOD

Chief Innovation Officer

Tel: (412) 573-5199

Address: 437 Grant St, Suite 2000, Pittsburgh, PA 15219



IMPORTANT: The contents of this email and any attachments are confidential and intended only for the individual or entity to whom they are addressed. If you have received this email by mistake, please notify the sender immediately, do not disclose the contents to anyone or make copies thereof, and delete all copies of the email.

________________________________

**Comment by bhadaway** [comment]
Since your designer didn't use a child theme, you won't be able to upgrade, as this overwrites all their customizations.

Options:

1. Just ignore the upgrade nag.
2. Edit the theme and make the version number a big number like 9999 to disable the upgrade nag or outright change the name of the theme to reflect the custom project (what I personally recommend).
3. Have your designer or someone new move all the customizations over to a child theme and then you'll be able to upgrade.

**Comment by iainelite** [comment]
Sir,

Thanks for getting back to me so promptly with the details. I am going to pass this information along to my marketing department to work out.

IAIN MACLEOD
Chief Innovation Officer
[(412) 573-5199]<tel:+(412)%20573-5199>[878-999-2771]<fax:+878-999-2771>[437 Grant Street, Suite 2000, Pittsburgh, PA ***@***.***,-79.9993871,17z/data=!3m1!4b1!4m5!3m4!1s0x8834f159ff23a791:0xf227f420b92bd75b!8m2!3d40.439227!4d-79.9971984>
***@***.******@***.***
***@***.******@***.******@***.***
CULTURE. THAT'S ELITE.

***@***.******@***.******@***.******@***.***<https://twitter.com/elite_transit>
IMPORTANT: The contents of this email and any attachments are confidential and intended only for the individual or entity to whom they are addressed. If you have received this email by mistake, please notify the sender immediately, do not disclose the contents to anyone or make copies thereof, and delete all copies of the email.

**Comment by bhadaway** [comment]
You're welcome and sounds good.
