### ISSUE TITLE
Link to concept in readme.txt dead

### ISSUE THREAD

**Issue by timurc** [tidythemes/blankslate#45]
Hey, 

this seems like what I want to use for the next website! Thanks.

Small thing: in the readme there is something that is supposed to be important to read: 

```
IMPORTANT — PLEASE READ: tidythemes.com/concept
```

But the link is dead. From what I gathered from the other closed issues: you don't own the domain anymore? I would be curious about this concept anyways. Anyways, "fixing" would obviously be deleting the link for now.

Edit: also the description links to [tidythemes.com/](http://tidythemes.com/) which seems to be unrelated to this repo at this point. Or is it part of some SEO deal that it needs to be there...? The link opened the podcast app on my macOS which was pretty confusing.

**Comment by bhadaway** [comment]
Updated.
