### ISSUE TITLE
Pages seem to jitter or reposition when refreshing at a point midway through the page

### ISSUE THREAD

**Issue by scotth527** [tidythemes/blankslate#47]
Hi, I built a site using this theme https://snapl.com/ and when scrolling towards the center and then hitting refresh the page seems to automatically show a scrolling effect to reposition. Is there anyway to remove this? I thought I had removed the jquery and javascript stuff but not sure if there are other functions creating this bug.

**Comment by scotth527** [comment]
I had WP Fastest cache on but disabling it didn't work. I'll try to disable
the lazy loading tomorrow and let you know.

Thanks for replying!


*Scott Huang*
University of Florida
305.333.4352

**Comment by scotth527** [comment]
I added this line of code to remove the lazy loading but it didn't seem to work. 

add_filter( 'wp_lazy_loading_enabled', '__return_false' );

**Comment by bhadaway** [comment]
Maybe you can capture the issue on video? Also, is this happening no matter what device, OS, and internet speed you're using?

**Comment by scotth527** [comment]
Yeah it's happened on mobile (android on chrome) edge, and chrome desktop.

I'll attach a video. Basically to recreate it you scroll to maybe like 60%
down to the page and you hit refresh you see a reposition of the page it
can sometimes go all the way up sometimes it jitters and move up a bit.

https://drive.google.com/drive/folders/1EnaAS5Bm7ih4IabET5i_99a0EDoudz1P?usp=sharing

*Scott Huang*
University of Florida
305.333.4352

**Comment by bhadaway** [comment]
That's definitely not a bug, and honestly, it's probably just normal "snap in" from loading/reloading a page. I don't think there's anything wrong or that needs to be fixed here. There's a lot of additional caching you may be able to do that could improve this, but we're talking about milliseconds.

Feel free to email me and I can show you one option that might help.

bhadaway@gmail.com
