### ISSUE TITLE
WordPress preview broken

### ISSUE THREAD

**Issue by matteomarchiori** [tidythemes/blankslate#48]
Hi,
I noticed something on the theme which breaks the "Preview" on [https://wordpress.org/themes/blankslate/](https://wordpress.org/themes/blankslate/).

The problem is that there is a loading spinner and a grey background which never disappear.

@bhadaway I explored also the other themes created by you, tried also with different browsers, but only BlankSlate presents this kind of behavior.

I used it as a base for another theme (W3CSSPress), and they have the same problem.

Till now I failed to identify the cause.
Do you know what it could be?

**Comment by bhadaway** [comment]
Not sure I understand.

You're referring to the theme demos on wordpress.org?

https://wp-themes.com/blankslate/

**Comment by matteomarchiori** [comment]
Exactly.

The theme loads correctly on wp-themes.com, but when you click "Preview" on wordpress.org it seems to not load completely

**Comment by bhadaway** [comment]
Most likely that's just a matter of browser privacy add-ons or settings that block pop-up elements. I've seen it before with this exact scenario. There's really nothing I can do from I end. Thanks for the heads up though.

**Comment by bhadaway** [comment]
It's likely just the unstyled nature of the theme that exposes whatever this little quirk is.
