### ISSUE TITLE
can name make different template for differnt page

### ISSUE THREAD

**Issue by myselfgaurav** [tidythemes/blankslate#5]
can name make different template for differnt page

**Comment by leecollings** [comment]
Please re-phrase your question, as it makes no sense. What's your issue?

**Comment by myselfgaurav** [comment]
ok see i added page set page attribute blog template . Now i set that age as post age from wordpress admin Reading. when i view page it uses template "Homepage" instead of what i set while creating that page

**Comment by leecollings** [comment]
I still have no idea what you're trying to do. Are you trying to set a static front page instead of a list of your blog articles?
