### ISSUE TITLE
Archive, Home Page and Single Post page Featured image

### ISSUE THREAD

**Issue by chrisrubb** [tidythemes/blankslate#50]
Hello,

I'd like to know how I can switch the location of the featured image with the `<h1>` on a post and the `<h2>` on an archive.

**Comment by bhadaway** [comment]
You'd have to remove the following from _entry.php_:

```
<?php if ( is_singular() ) { echo '<h1 class="entry-title" itemprop="headline">'; } else { echo '<h2 class="entry-title">'; } ?>
<a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>" rel="bookmark"><?php the_title(); ?></a>
<?php if ( is_singular() ) { echo '</h1>'; } else { echo '</h2>'; } ?>
```

And then add it under the featured image code in both _entry-content.php_ and _entry-summary.php_. Be sure to use a child theme if you intend on getting updates.

**Comment by chrisrubb** [comment]
Thank you very much for your response. Could you please indicate exactly where I am to place the code? I placed it at the end of the loop in entry-summary as well as on entry-content and my post titles are not showing up now.

**Comment by bhadaway** [comment]
Now that I think about it, you'll probably want to remove the entire header from _entry.php_:

```
<header>
<?php if ( is_singular() ) { echo '<h1 class="entry-title" itemprop="headline">'; } else { echo '<h2 class="entry-title">'; } ?>
<a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>" rel="bookmark"><?php the_title(); ?></a>
<?php if ( is_singular() ) { echo '</h1>'; } else { echo '</h2>'; } ?>
<?php edit_post_link(); ?>
<?php if ( !is_search() ) { get_template_part( 'entry', 'meta' ); } ?>
</header>
```

And then add it on line 5 in _entry-content.php_ and also line 5 for _entry-summary.php_.

**Comment by chrisrubb** [comment]
That worked like a charm, thank you!

**Comment by bhadaway** [comment]
You're welcome.
