### ISSUE TITLE
Issues with page width

### ISSUE THREAD

**Issue by DCollepa** [tidythemes/blankslate#51]
Hello,

I use BlankSlate in my website and manage it with WordPress.

I'm trying to adjust all my landing pages to the same page width, however I can not find the way to customize the category page in order to resize the max width.

Can anyone help me out with this?

Thanks!

**Comment by bhadaway** [comment]
If you want to target category pages only:

```
.category #wrapper {
	max-width: 800px;
	margin: 0 auto;
}
```

or:

```
.category #content {
	max-width: 800px;
	margin: 0 auto;
}
```

**Comment by DCollepa** [comment]
Thanks Bryan!
I emailed you, hope you get the chance to check it out.

**Comment by bhadaway** [comment]
Don't see any emails related to this.
