### ISSUE TITLE
Compatibility with WooCommerce 

### ISSUE THREAD

**Issue by DCollepa** [tidythemes/blankslate#52]
Back in February, BlankSlate had compatibility issues with WooCommerce which caused our website to crash.
WooCommerce gave us a notification, which reads something like this:

"Your theme contains outdated copies of some WooCommerce template files. You may need to update these files to ensure they are compatible with the current version of WooCommerce. Suggestions to fix this:
1. Update your theme to the latest version. If no update is available, contact your theme author to ask about compatibility with the current version of WooCommerce.
2. If you have copied over a template file to change something, then you will need to copy the new version of the template file and apply your changes again."

We managed to fix it but now can't update the theme.

@bhadaway is there any way to go over this with you directly?

**Comment by bhadaway** [comment]
BlankSlate doesn't provide a _woocommerce.php_ template file, so I assume you had to update _page.php_?

If you need private support, yes, you may email me at: bhadaway@gmail.com.

**Comment by DCollepa** [comment]
Thanks! Already did, please check the spam folder if you can't find my email. It's from the domain artwks.co

**Comment by bhadaway** [comment]
Responded.
