### ISSUE TITLE
BlankSlate and ACF

### ISSUE THREAD

**Issue by eschiaroli** [tidythemes/blankslate#54]
Hi, Is the theme compatible with Advanced Custom Field? I set up some fields in ACF, with other themes when I edit the article I can see the fields and I can fill them, with Blankslate I can’t.

**Comment by bhadaway** [comment]
I can't think of any reason it wouldn't be.

BlankSlate is a classic theme, so it's possible that you also need the Classic Editor:

https://wordpress.org/plugins/classic-editor/

If that doesn't help, the devs on ACF's side might know:

https://support.advancedcustomfields.com/

Perhaps special integration is required.

**Comment by eschiaroli** [comment]
Hi Bhadaway,

Thank you for your response. I followed your advice, but unfortunately, it didn't work. To be sure, I reinstalled BlankSlate without making any changes, and I still can't see the fields.

I also attempted it with the Twenty Four theme, and the fields are visible (the ACF fields are spotify URL and youtube). 

![ok](https://github.com/tidythemes/blankslate/assets/6361847/c733b643-eba7-4618-a64c-12bc298c43a8)

**Comment by eschiaroli** [comment]
If I add this in function.php I can see the custom fields

`add_action('acf/init', 'blankslate_acf_init');
function blankslate_acf_init() {
    if( function_exists('acf_add_local_field_group') ) {
        acf_add_local_field_group(array(
            'key' => 'group_6544d4dca9626',
            'title' => 'Custom Fields',
            'fields' => array(
                // Aggiungi qui i tuoi campi ACF
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
        ));
    }
}`

**Comment by bhadaway** [comment]
Thanks for sharing the solution.
