### ISSUE TITLE
Question: is blankslate the new trueres?

### ISSUE THREAD

**Issue by bdelamotte** [tidythemes/blankslate#56]
I inherited a new Wordpress project and found a link to `https://github.com/tidythemes/trueres` which is no longer there. Is `blankslate` the new version of `trueres`?

**Comment by bhadaway** [comment]
https://github.com/tidythemes/trueres never existed.

What the person before you did is take BlankSlate as a starting point for their project (a valid use for the theme) and they named their theme Trueres, which they then did a find and replace all for the word **blankslate** with **trueres**.

BlankSlate is intentionally bare-bones, so if the theme is causing you any issues, it's likely from custom code added in after the fact. I'm still willing to help if that's the case.

If you're simply trying to make sure that the theme is up-to-date, you can't/don't want to update it in this context. Simply consider it a custom theme.

**Comment by bdelamotte** [comment]
Thank you @bhadaway for the explanation and detailed answer. Looks like that is exactly what they did and then added a bunch more stuff to it for WooCommerce and such. They got 5 or so custom Wordpress plugins as well that look to be poorly written and the site randomly crashes, so I've been reverse engineering how they built it.

Through this process, I am glad I learned about your blankslate theme as now I can use it in the future for other Wordpress projects!

**Comment by bhadaway** [comment]
You're welcome.
