### ISSUE TITLE
transition: all in style.css

### ISSUE THREAD

**Issue by tobiasger** [tidythemes/blankslate#8]
I noticed that the recent update of the theme has the following added to the `style.css`:

```
* {
    ...
    transition: all 0.5s ease
}
```
I'm having trouble with overwriting this rule. I try to apply `transition:none;` to my own CSS with a child theme. And that disables the transitions, but if I try to add a custom transition to an element, it's not applied. So the `transition:none;` on `*` seems to overwrite any other rule. Am I doing this wrong? And would it be an idea to disable this rule in the `style.css` in future releases since it feels bothersome to have transition added to all elements?

Edit: Sorry, I had the wrong elements selected when applying new transitions, so there's actually no problem with adding new transitions after disabling them with `* {transition:none;}`. But I still think it should be up to the person using the theme to determine if the `transition: all 0.5s ease` should be there at all and not have it there by default. Maybe it's just me?

**Comment by leecollings** [comment]
I've noticed there have been lots of little things sneaking into Blankslate over the past couple of years that have actually (in my opinion) started to take it away from what is' meant to be.. a blank slate.

Why is there a transition effect on ALL elements? This is a preferred styling option that shouldn't be there by default.

I've been forced to fork this into my own repo and keep as bare as it used to be, I have to say, I really don't like where it is anymore it's getting very cluttered.

**Comment by pattonwebz** [comment]
@leecollings if you have forked this you might want to look at the issue I just posted in #9 . (also HI!!! what a coincidence to see you again so soon :) )

**Comment by leecollings** [comment]
Thanks for this. I used to fork it actually, then realised every time I
went to use it for a project I was deleting most of it and reformatting it,
so I got rid of it.

I’ll probably fork it again and get it going again, they’ve added a lot
more junk in the original now that I just think is totally unneccessary.

Thanks for the heads up.

**Comment by bhadaway** [comment]
Agreed and sorry! Was not intentional at all. It was an oversight on my part.

Please see: https://github.com/tidythemes/blankslate/issues/10.

Thanks
