### ISSUE TITLE
Duplicate calls to `the_content()`

### ISSUE THREAD

**Issue by pattonwebz** [tidythemes/blankslate#9]
Hi,

I am on the wordpress.org theme review team and someone reported that this theme has duplicate calls inside of `entry-content.php`. I figured I would create an issue here to let you know.

https://github.com/tidythemes/blankslate/blob/7a0cd0599bb7a1631b9996c5390ce9e89c11d697/entry-content.php#L5-L9

**Comment by bhadaway** [comment]
Thank you for the heads up!

Please see: https://github.com/tidythemes/blankslate/issues/10.
